2016-10-30 21:58:59,124 [Thread-8:19976] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Temp\blog_project\blog\views.py", line 19, in index
    return render(request, 'index.html', locals())
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'SITE_NAME'
2016-10-30 21:59:21,447 [Thread-2:20160] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Temp\blog_project\blog\views.py", line 19, in index
    return render(request, 'index.html', locals())
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'SITE_NAME'
2016-10-31 23:16:28,079 [Thread-16:5988] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-11-02 22:50:27,140 [Thread-10:3328] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-11-02 23:12:26,517 [Thread-29:20628] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:12:59,796 [Thread-48:4948] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:15:04,821 [Thread-72:19416] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:15:30,717 [Thread-91:19060] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:18:40,849 [Thread-101:20460] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/index.js.map/
2016-11-02 23:18:43,984 [Thread-103:22436] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/index.js.map
2016-11-02 23:18:48,318 [Thread-107:11188] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/add/index.js.map/
2016-11-02 23:19:46,552 [Thread-127:21924] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/add/index.js.map/
2016-11-02 23:37:39,668 [Thread-2:18072] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\software\Python\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\Temp\blog_project\blog_project\urls.py", line 23
SyntaxError: Non-ASCII character '\xe8' in file E:\Temp\blog_project\blog_project\urls.py on line 23, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
2016-11-02 23:37:57,265 [Thread-3:21716] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-02 23:38:07,250 [Thread-2:20952] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-02 23:38:34,029 [Thread-2:17732] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-02 23:40:02,667 [Thread-2:18048] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-03 12:06:58,148 [Thread-27:2652] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-11-03 12:20:09,960 [Thread-49:5984] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 12:23:18,757 [Thread-58:7444] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 19, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'locd'
2016-11-03 14:37:37,098 [Thread-76:7468] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-11-03 14:59:21,214 [Thread-2:9756] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Temp\blog_project\blog_project\urls.py", line 18, in <module>
    from blog.views import index
  File "D:\Temp\blog_project\blog\views.py", line 21
SyntaxError: Non-ASCII character '\xe4' in file D:\Temp\blog_project\blog\views.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
2016-11-03 14:59:47,188 [Thread-8:3744] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 28, in index
    page = int(request.Get.get('page', 1))
AttributeError: 'WSGIRequest' object has no attribute 'Get'
2016-11-03 15:00:17,377 [Thread-2:8428] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 34, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'article.title', expected 'empty' or 'endfor'
2016-11-03 15:01:15,871 [Thread-6:10172] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 34, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'article.title', expected 'empty' or 'endfor'
2016-11-03 15:01:29,144 [Thread-9:6704] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 34, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'article.title', expected 'empty' or 'endfor'
2016-11-03 15:05:24,621 [Thread-14:2776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 34, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endblock', expected 'empty' or 'endfor'
2016-11-03 15:16:03,391 [Thread-2:9016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 35, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '+1' from 'page+1'
2016-11-03 15:20:28,474 [Thread-4:5948] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 35, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 647, in resolve
    obj = self.var.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 847, in _resolve_lookup
    current = current()
  File "C:\Python27\lib\site-packages\django\core\paginator.py", line 138, in next_page_number
    return self.paginator.validate_number(self.number + 1)
  File "C:\Python27\lib\site-packages\django\core\paginator.py", line 43, in validate_number
    raise EmptyPage('That page contains no results')
EmptyPage: That page contains no results
2016-11-03 15:21:45,413 [Thread-9:4140] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 35, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 647, in resolve
    obj = self.var.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 847, in _resolve_lookup
    current = current()
  File "C:\Python27\lib\site-packages\django\core\paginator.py", line 138, in next_page_number
    return self.paginator.validate_number(self.number + 1)
  File "C:\Python27\lib\site-packages\django\core\paginator.py", line 43, in validate_number
    raise EmptyPage('That page contains no results')
EmptyPage: That page contains no results
2016-11-03 15:48:05,028 [Thread-2:5880] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 36, in index
    for archive in archive_list:
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1296, in __iter__
    raise InvalidQuery('Raw query must include the primary key')
InvalidQuery: Raw query must include the primary key
2016-11-03 16:03:53,338 [Thread-2:7332] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 43, in index
    cursor.excute("SELECT DISTINCT( to_char(date_publish,'yyyy-mm-dd')) as publib_date FROM blog_article ORDER BY publib_date desc;")
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 24, in __getattr__
    cursor_attr = getattr(self.cursor, attr)
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'excute'
2016-11-03 16:43:36,928 [Thread-2:2408] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 49, in index
    for article in Article.objects.distinct_date():
  File "D:\Temp\blog_project\blog\models.py", line 45, in distinct_date
    date_list = self.values['date_publish']
TypeError: 'instancemethod' object has no attribute '__getitem__'
2016-11-03 16:45:44,359 [Thread-2:6344] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 49, in index
    for article in Article.objects.distinct_date():
  File "D:\Temp\blog_project\blog\models.py", line 48, in distinct_date
    set.add(date)
TypeError: descriptor 'add' requires a 'set' object but received a 'str'
2016-11-03 16:46:12,943 [Thread-2:10388] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 49, in index
    for article in Article.objects.distinct_date():
  File "D:\Temp\blog_project\blog\models.py", line 48, in distinct_date
    distinct_list.add(date)
AttributeError: 'tuple' object has no attribute 'add'
2016-11-03 16:54:51,398 [Thread-12:5572] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 16:55:58,121 [Thread-23:10220] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:01:00,605 [Thread-24:4636] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 50, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 211, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'archive' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-11-03 17:01:01,226 [Thread-25:9136] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:01:55,372 [Thread-26:1644] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 50, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 211, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'archive' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-11-03 17:01:55,704 [Thread-27:10308] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:02:23,201 [Thread-28:8392] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 50, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 211, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'archive' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-11-03 17:02:23,549 [Thread-29:9136] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:03:56,851 [Thread-30:11064] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 50, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 211, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'archive' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-11-03 17:03:57,193 [Thread-31:5468] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:04:30,805 [Thread-32:10576] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 50, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 211, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'archive' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2016-11-03 17:04:31,243 [Thread-33:8788] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:05:23,946 [Thread-44:10876] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:05:33,921 [Thread-45:10976] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive
2016-11-03 17:05:34,098 [Thread-46:10744] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:05:36,374 [Thread-47:4200] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:09:16,516 [Thread-2:8348] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Temp\blog_project\blog_project\urls.py", line 18, in <module>
    from blog.views import index, archive
  File "D:\Temp\blog_project\blog\views.py", line 56
    article_list = Article.objects.filter(date_publish_icontains=year+'-'month)
                                                                             ^
SyntaxError: invalid syntax
2016-11-03 17:09:16,743 [Thread-3:7084] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index.js.map
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Temp\blog_project\blog_project\urls.py", line 18, in <module>
    from blog.views import index, archive
  File "D:\Temp\blog_project\blog\views.py", line 56
    article_list = Article.objects.filter(date_publish_icontains=year+'-'month)
                                                                             ^
SyntaxError: invalid syntax
2016-11-03 17:09:32,553 [Thread-14:11236] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:09:37,584 [Thread-15:9064] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive
2016-11-03 17:09:37,773 [Thread-16:10740] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:10:31,362 [Thread-2:9424] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive
2016-11-03 17:10:31,578 [Thread-3:9520] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:11:01,477 [Thread-2:10284] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 56, in archive
    article_list = Article.objects.filter(date_publish_icontains=year+'-'+month)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1144, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1030, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1386, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'date_publish_icontains' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2016-11-03 17:11:01,763 [Thread-3:8004] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:12:30,683 [Thread-2:9504] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 56, in archive
    article_list = Article.objects.filter(date_publish_icontains=year+'-'+month)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1144, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1030, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1386, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'date_publish_icontains' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2016-11-03 17:12:30,946 [Thread-3:8568] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:13:47,138 [Thread-3:8512] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:15:12,440 [Thread-2:7424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 57, in archive
    article_list = Article.objects.filter(name_contains=year+'-'+month)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1144, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1030, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1386, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'name_contains' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2016-11-03 17:15:12,703 [Thread-3:11096] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:16:32,013 [Thread-3:7668] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:19:19,844 [Thread-14:9600] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:20:12,096 [Thread-12:3720] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:20:14,430 [Thread-14:6936] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:20:20,571 [Thread-16:10968] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:35:51,476 [Thread-2:10620] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Temp\blog_project\blog\views.py", line 52, in archive
    return render(request, 'archive.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 208, in render
    with context.bind_template(self):
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\django\template\context.py", line 235, in bind_template
    updates.update(processor(self.request))
  File "D:\Temp\blog_project\blog\views.py", line 16, in global_setting
    return render(locals())
TypeError: render() takes at least 2 arguments (1 given)
2016-11-03 17:35:51,812 [Thread-3:10632] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:39:23,381 [Thread-12:9328] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:50:58,795 [Thread-23:10620] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:51:53,132 [Thread-34:10456] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:52:24,171 [Thread-45:10432] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:52:31,782 [Thread-47:1644] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:53:03,364 [Thread-62:4040] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:53:05,322 [Thread-64:8152] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:53:09,598 [Thread-66:10728] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 17:57:29,214 [Thread-12:7584] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:00:15,019 [Thread-12:8896] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:04:36,950 [Thread-12:6292] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:05:22,785 [Thread-23:7824] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:07:57,489 [Thread-25:7580] [django.request:170] [base:get_response] [WARNING]- Not Found: /css/base.css
2016-11-03 18:07:57,503 [Thread-26:10296] [django.request:170] [base:get_response] [WARNING]- Not Found: /css/index.css
2016-11-03 18:07:57,506 [Thread-27:5628] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/jquery.min.js
2016-11-03 18:07:57,506 [Thread-28:11072] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/sliders.js
2016-11-03 18:07:57,517 [Thread-29:3912] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/nav.js
2016-11-03 18:07:57,578 [Thread-31:10460] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2016-11-03 18:07:57,578 [Thread-32:2768] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2016-11-03 18:07:57,578 [Thread-30:9832] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2016-11-03 18:07:57,579 [Thread-33:8536] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2016-11-03 18:07:58,157 [Thread-34:11124] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:16:32,079 [Thread-3:7696] [django.request:170] [base:get_response] [WARNING]- Not Found: /css/base.css
2016-11-03 18:16:32,085 [Thread-4:8760] [django.request:170] [base:get_response] [WARNING]- Not Found: /css/index.css
2016-11-03 18:16:32,086 [Thread-5:10936] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/jquery.min.js
2016-11-03 18:16:32,105 [Thread-6:8516] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/sliders.js
2016-11-03 18:16:32,125 [Thread-7:4924] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/nav.js
2016-11-03 18:16:32,201 [Thread-8:7668] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2016-11-03 18:16:32,203 [Thread-9:4988] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2016-11-03 18:16:32,203 [Thread-10:2620] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2016-11-03 18:16:32,211 [Thread-11:10856] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2016-11-03 18:16:32,221 [Thread-12:10772] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:18:19,362 [Thread-14:9720] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:18:26,763 [Thread-15:10664] [django.request:170] [base:get_response] [WARNING]- Not Found: /css/base.css
2016-11-03 18:18:26,765 [Thread-16:7368] [django.request:170] [base:get_response] [WARNING]- Not Found: /css/index.css
2016-11-03 18:18:26,782 [Thread-17:5628] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/jquery.min.js
2016-11-03 18:18:26,783 [Thread-18:10184] [django.request:170] [base:get_response] [WARNING]- Not Found: /js/sliders.js
2016-11-03 18:18:26,852 [Thread-19:10288] [django.request:170] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2016-11-03 18:18:26,920 [Thread-20:3752] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
2016-11-03 18:18:51,150 [Thread-27:10248] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.js.map
